添加网安院大三课程
andream7/cuit_sharing pull request #74
Opened 2024-05-06 14:28 UTC by tiansuo114

网安院 网络工程专业
路由域交换技术
无线网络技术
移动应用开发

2024-05-10 12:21 UTC, CSZongzi approved these changes

2024-05-10 12:25 UTC, CSZongzi requested changes
@tiansuo114 你需要对 git commit 进行签名，可以参考 https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits 的指示，亦或是通过 GitHub 网站上传文件（这将使得 commit 使用 GitHub 的 GPG 私钥进行签名）

2024-05-14 06:25 UTC, tiansuo114 commented
> @tiansuo114 你需要对 git commit 进行签名，可以参考 https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits 的指示，亦或是通过 GitHub 网站上传文件（这将使得 commit 使用 GitHub 的 GPG 私钥进行签名）

现在是verified,粽✌再看看

2024-05-17 07:59 UTC, CSZongzi approved these changes

2024-05-17 07:59 UTC, merged